// Manuscrito para Journal of Water and Environment Technology (JWET), borrador en español.
// Marcado: *itálica*, **negrita**. Las referencias van numeradas por orden de aparición.
module.exports = {
  titulo: "Kenti Calidad de Agua: una herramienta de código abierto para evaluar análisis de agua frente a múltiples marcos normativos con datos incompletos",
  autores: "Carlos María Flores",
  afiliacion: "Atoj S.A.S., Tafí Viejo, Tucumán, Argentina",
  palabras: "Palabras clave: calidad del agua; niveles guía; índice de calidad de agua; datos censurados; software de código abierto",
  correspondencia: [
    "Autor de correspondencia: Carlos María Flores",
    "Dirección: Lomalinda J6, Tafí Viejo, Tucumán, Argentina",
    "Teléfono: -54 3816470001",
    "Correo electrónico: carlosmaria.flores@gmail.com",
    "ORCID: 0009-0000-8959-4738",
  ],
  resumen: "Los informes de calidad de agua comparan resultados de laboratorio con niveles guía de marcos normativos que difieren en unidades, forma química de expresión, límites condicionales y parámetros exigidos, con datos a menudo incompletos o censurados. Se presenta Kenti Calidad de Agua, una aplicación local de código abierto que lee informes de laboratorio heterogéneos, convierte 63 unidades a una unidad canónica mediante masas molares, densidad y molalidad, y evalúa cada muestra frente a 21 normas de Argentina, Japón, la OMS, la Unión Europea, Estados Unidos, Canadá, Australia y Nueva Zelanda y la FAO. Ningún parámetro es obligatorio: los faltantes y los resultados no concluyentes por el límite de detección se informan como salvedades. También calcula el índice de calidad de agua del CCME, el balance iónico, la relación de adsorción de sodio y el índice de Langelier. Frente a una implementación independiente en Python, con 1000 casos simulados por procedimiento, las diferencias máximas fueron de 4,1 × 10⁻¹⁶ (relativa) en las conversiones y de 2,8 × 10⁻¹⁴ en el índice, y las decisiones coincidieron siempre. Con datos simulados, el índice calculado con tres variables cambió de categoría respecto del obtenido con 16 en el 70 % de los subconjuntos.",
  secciones: [
    {h: "INTRODUCCIÓN", p: [
      "La evaluación de la calidad del agua en estudios de impacto ambiental, líneas de base y monitoreos termina, casi siempre, en una comparación: cada resultado de laboratorio frente al nivel guía que corresponde al uso del agua. En la práctica rara vez hay un único marco de referencia. Un mismo informe puede tener que responder a la norma nacional, a las guías de la Organización Mundial de la Salud (OMS) que exigen financiadores y estándares corporativos, y a normas específicas para riego, bebida de ganado o protección de la vida acuática [1–12].",
      "Esos marcos no son intercambiables. El nitrato, cuyo valor guía se basa en la metahemoglobinemia del lactante [1, 37], se limita a 50 mg/L expresado como ion NO₃⁻ en las guías de la OMS y en la Unión Europea [1, 2], pero a 10 mg/L expresado como nitrógeno en Estados Unidos y en Japón [3, 7], es decir, 44,3 mg/L como NO₃⁻; el Código Alimentario Argentino fija 45 mg/L [4]. El boro admite 2,4 mg/L en las guías de la OMS y en Argentina desde 2023, 1,5 mg/L en la Unión Europea y 1,0 mg/L en Japón [1, 2, 4, 7]. Algunos límites dependen de la muestra o del sitio: los de cadmio, cobre, níquel y plomo para vida acuática del Decreto 831/93 cambian con la dureza del agua [5], y el de fluoruro del Código Alimentario, con la temperatura media anual del lugar [4]. Además, cada marco distingue entre valores sanitarios y valores de aceptabilidad, indicadores o secundarios, que no tienen el mismo peso en un diagnóstico.",
      "Los datos, por su parte, rara vez están completos. Cada laboratorio informa un conjunto distinto de parámetros, en unidades distintas (mg/L, µg/L, meq/L, ppm, o molalidad en las salmueras de los salares altoandinos [36]), cuya equivalencia depende de la masa molar, la carga y la densidad [38], y con valores censurados por el límite de detección («<0,005», «ND»), cuyo tratamiento requiere reglas explícitas: sustituirlos por la mitad del límite o por cero puede sesgar las estadísticas [14, 30–32]. Los equipos de campo informan la conductividad a veces compensada a 25 °C y a veces no, y la conductividad varía cerca de un 2 % por grado [39]. Todo esto suele resolverse en planillas de cálculo, donde los errores de fórmula y de transcripción son frecuentes y persisten incluso en la literatura publicada [13, 43].",
      "Los índices de calidad de agua resumen la comparación en un número; desde el propuesto por Horton [24] se han desarrollado decenas, con distintas formas de selección de variables, normalización, ponderación y agregación [16, 25, 26], y todos enfrentan problemas de eclipsamiento y ambigüedad al agregar [27]. El del Consejo Canadiense de Ministros del Ambiente (CCME) se usa ampliamente porque admite cualquier conjunto de variables y cualquier conjunto de objetivos [15, 16, 28, 29]. Esa flexibilidad tiene un costo poco discutido en la práctica: el valor depende de qué variables se incluyeron, y dos sitios o dos campañas con conjuntos distintos no son directamente comparables.",
      "Hay herramientas abiertas y ampliamente usadas para la especiación y los índices de saturación, como PHREEQC [46], o para los diagramas hidroquímicos, como WQChartPy [47], pero no están orientadas a comparar una muestra con varios marcos normativos a la vez ni a declarar qué parámetros faltan para cada uno.",
      "Este trabajo presenta Kenti Calidad de Agua, un módulo de código abierto de Kenti [22] diseñado con cuatro principios: (i) ningún parámetro es obligatorio, pero todo faltante se declara; (ii) cada límite es trazable a su fuente, con su escala (nacional, regional o internacional) y su tipo; (iii) las conversiones y decisiones son explícitas y reproducibles, sin conexión y con datos en formato abierto; y (iv) cada cálculo está verificado contra una implementación independiente, siguiendo las prácticas recomendadas para el software científico [42, 44, 45]. Se describen el diseño, las reglas de decisión y la verificación numérica, y se ilustran dos consecuencias prácticas con datos simulados: la heterogeneidad de los veredictos entre marcos para una misma muestra y la sensibilidad del índice del CCME al subconjunto de variables medidas.",
    ]},
    {h: "MATERIALES Y MÉTODOS", sub: [
      {h: "Arquitectura", p: [
        "Kenti Calidad de Agua usa el mismo lanzador que los demás módulos de Kenti [22]: un ejecutable escrito en Go 1.24, sólo con la biblioteca estándar, que levanta un servidor HTTP en la dirección local 127.0.0.1 y abre la interfaz en una ventana de Edge o Chrome. La interfaz y todos los cálculos están en HTML, CSS y JavaScript embebidos en el ejecutable; los datos no salen del equipo y se guardan en un archivo JSON legible, con respaldo automático. La aritmética es de doble precisión (IEEE 754). La interfaz está en español o en inglés, a elección del usuario; el idioma cambia los textos, los nombres de parámetros y normas y el formato de los números, pero no los datos ni los cálculos. El programa tiene siete pestañas: datos, evaluación normativa, índice de calidad de agua, iones y derivados, conversor de unidades, controles y normas (Fig. 1). Los resultados se exportan a un libro de Excel con los datos originales, los datos convertidos, la evaluación de cada parámetro frente a cada norma, las salvedades, el índice, los cálculos derivados, los controles y la tabla de niveles guía usada, con su cita.",
      ]},
      {h: "Lectura de los datos", p: [
        "El programa acepta tablas pegadas desde una planilla o archivos .xlsx, en dos disposiciones: una muestra por fila, o el formato habitual de los informes de laboratorio, con los parámetros en filas y las muestras en columnas. La disposición se detecta comparando cuántos nombres de parámetros se reconocen en la mejor fila y en la mejor columna de la tabla. Los encabezados se reconocen por expresiones regulares sobre el texto normalizado (sin tildes ni mayúsculas), con el nombre, el símbolo químico o las siglas habituales en español e inglés. La unidad se lee del propio encabezado, de una fila de unidades o de una columna «Unidad»; también se leen la forma química («como N», «N-NO₃»), la fracción (total o disuelta) y una columna de límite de detección. Las filas y columnas con niveles guía, métodos o promedios se descartan.",
        "Cada columna declara su separador decimal (coma o punto), detectado a partir de todos sus valores. Los valores se clasifican en numéricos, menores que el límite de detección («<0,005», «ND» con el límite de la columna), mayores que un valor («>2400»), ausencia o presencia (en microbiología) y sin dato («s/d», «–», celda vacía). Los valores que no se pueden leer se marcan como error y no se evalúan.",
      ]},
      {h: "Unidades y formas químicas", p: [
        "Cada parámetro tiene una unidad canónica: mg/L de la forma iónica o elemental habitual para las concentraciones, µS/cm para la conductividad eléctrica (CE), °C para la temperatura, mg/L como CaCO₃ para la dureza y la alcalinidad, y UFC/100 mL para los indicadores bacterianos. El programa reconoce 63 unidades en 13 familias. Para las concentraciones, la conversión de un valor *x* a mg/L de la forma canónica, de masa molar *M* y carga *z*, sigue su definición [38]:",
      ], eq: [
        "masa por volumen (mg/L, µg/L, g/L, % m/v):   C = f · x · M / M_forma",
        "masa por masa (ppm, ppb, mg/kg, % m/m):   C = f · x · ρ · M / M_forma",
        "molar (mol/L, mmol/L, µmol/L):   C = f · x · M · 1000",
        "molal (mol/kg, mmol/kg):   C = f · x · M · 1000 · (ρ · 10⁶ − SDT) / 10⁶",
        "equivalentes (meq/L, µeq/L):   C = f · x · (M / z) · 1000",
      ], p2: [
        "donde *f* es el factor de la unidad, *M*<sub>forma</sub> es la masa molar de la forma en que se expresó el valor (por ejemplo, 14,007 g/mol si el nitrato se informó como N), ρ es la densidad de la muestra en g/mL y SDT, los sólidos disueltos totales en mg/L. Las masas molares son las de la IUPAC [23]. Si falta la densidad, se usa 1 g/mL y se advierte; la advertencia es más fuerte si los SDT superan 10 g/L o la CE supera 15 mS/cm, porque en salmueras (1,1 a 1,25 g/mL) la diferencia entre ppm y mg/L supera el 10 %. La resistividad se convierte como inversa de la conductividad, y la CE medida sin compensar puede llevarse a 25 °C con la corrección lineal CE<sub>25</sub> = CE<sub>*t*</sub> / [1 + α (*t* − 25)], con α = 2 %/°C por omisión y configurable [17, 39]. Las mismas funciones alimentan un conversor para valores sueltos.",
      ]},
      {h: "Base de niveles guía", p: [
        "La base incluye 21 normas con 373 valores guía (Tabla 1), transcritos de los textos oficiales o, cuando no fue posible, cotejados en al menos dos fuentes secundarias [1–12]. Para Japón se incorporaron las normas de agua potable vigentes desde el 1 de abril de 2026 (52 ítems, de los cuales Kenti incluye los inorgánicos, generales y microbiológicos) [7], los estándares ambientales de salud humana y de ambiente de vida para ríos por clase de uso [8] y la norma de agua para riego de arroz [9]. Las tablas del Anexo IV de la Ley 24.585, que rige la actividad minera en Argentina, se cargaron con los valores del Decreto 831/93, del que provienen [5, 6], como normas separadas para que el informe cite el marco que corresponde.",
        "Cada valor guía lleva su forma química de expresión, su tipo (sanitario, de aceptabilidad, indicador, secundario, nivel de acción, operativo o grado de restricción) y una nota con las condiciones de aplicación. Los límites condicionales se resuelven para cada muestra: la dureza medida o, si falta, la calculada con calcio y magnesio, para los metales de la tabla 2 del Decreto 831/93 [5]; el pH, el calcio y el carbono orgánico disuelto para el aluminio de esa tabla; la temperatura media anual del sitio para el fluoruro del Código Alimentario [4]; la especie para el cobre y los sólidos disueltos en bebida de ganado [10, 11]; y la clase de río para los estándares japoneses [8]. Si falta el dato que condiciona el límite, se usa el valor más exigente y se declara como salvedad.",
        "La transcripción detectó una inconsistencia que Kenti hace visible en lugar de corregir: la tabla 6 del Decreto 831/93 fija 50 µg/L de cinc para bebida de ganado, mientras que la fuente que cita establece 50 mg/L. El programa compara con el valor impreso y lo advierte en la nota del límite.",
      ]},
      {h: "Reglas de decisión", p: [
        "Cada par muestra–parámetro se clasifica frente a cada límite en uno de seis estados: cumple, supera, restricción ligera a moderada o severa (sólo para las guías de riego de la FAO, que usan dos umbrales [12]), no concluyente y sin dato. Un valor numérico supera si es mayor que el máximo o menor que el mínimo; el valor igual al límite cumple. Un valor menor que el límite de detección (LD) cumple si el LD no supera el máximo, y es no concluyente si lo supera; frente a un mínimo, supera si el LD no alcanza el mínimo. Un valor informado como «mayor que *x*» supera sólo si *x* ya alcanza el máximo. La presencia de un indicador bacteriano supera un límite de ausencia. Para las normas que limitan la suma de nitrato y nitrito como N [7, 10], la suma se calcula con los valores disponibles y los menores que el LD cuentan como cero, lo que se declara.",
        "Cada muestra recibe un veredicto por norma: «cumple» si se evaluaron todos los parámetros de la norma y todos cumplen; «cumple en lo medido» si todo lo evaluado cumple pero faltan parámetros o hay resultados no concluyentes; «supera valores no sanitarios» si sólo se exceden valores de aceptabilidad, indicadores, secundarios u operativos, o hay restricción ligera; y «no cumple» si se excede un valor sanitario o hay restricción severa. Junto al veredicto se generan las salvedades: cuántos parámetros de la norma se evaluaron y cuáles faltan, qué parámetros decisivos para el uso no se midieron (por ejemplo, la microbiología en agua de consumo), qué resultados no son concluyentes y por qué, qué condiciones se supusieron, qué valores se calcularon en lugar de medirse y qué conversiones usaron una densidad supuesta. El programa también redacta un borrador del texto de resultados para el informe.",
      ]},
      {h: "Índice de calidad de agua y cálculos derivados", p: [
        "El índice del CCME [15] se calcula por sitio y para el conjunto de muestras, con los objetivos de la norma elegida resueltos para cada muestra:",
      ], eq: [
        "F₁ = 100 · (variables que fallan) / (variables evaluadas)",
        "F₂ = 100 · (resultados que fallan) / (resultados evaluados)",
        "excursión = valor / objetivo − 1 (máximos) u objetivo / valor − 1 (mínimos);   nse = Σ excursiones / resultados evaluados",
        "F₃ = nse / (0,01 · nse + 0,01);   ICA = 100 − √(F₁² + F₂² + F₃²) / 1,732",
      ], p2: [
        "Los resultados no concluyentes y los indicadores bacterianos con objetivo de ausencia quedan fuera, porque con objetivo cero la excursión no está definida; ambos se informan. El programa advierte cuando hay menos de cuatro variables o de cuatro muestreos, como recomienda el manual [15], y cuando los sitios comparados no tienen el mismo conjunto de variables.",
        "Con los iones mayoritarios se calculan el balance iónico con los criterios de aceptación de APHA 1030 E [17, 41], la facies hidroquímica, la dureza calculada, la relación de adsorción de sodio (RAS), la clase de Riverside [18], la restricción de infiltración de la FAO según RAS y CE [12], los índices de Langelier [19] y de Ryznar [20], y la regla de la OMS y de la Unión Europea [nitrato]/50 + [nitrito]/3 ≤ 1 [1, 2]. Estos cálculos alimentan también los controles de calidad de los datos: balance iónico fuera de criterio, relación SDT/CE fuera de 0,55–0,75 [38, 40], dureza medida y calculada discordantes, fracción disuelta mayor que la total, valores negativos o fuera de rango, unidades probablemente equivocadas y números ambiguos por el separador de miles.",
      ]},
      {h: "Verificación numérica", p: [
        "Las funciones de cálculo se ejecutaron sin modificaciones en Node.js sobre 1000 casos simulados por procedimiento (semilla 20260923) y sus resultados se compararon con una implementación independiente en Python y NumPy [21, 42], escrita a partir de las definiciones y no del código de Kenti. Los casos cubrieron: (i) conversiones de 15 parámetros entre 20 unidades de concentración, con formas N y P, densidades de 0,998 a 1,25 g/mL y SDT de hasta 350 g/L; (ii) decisiones frente a máximos, mínimos, rangos y grados de restricción, con valores numéricos, menores que el LD, mayores que un valor y presencia, incluidos objetivos de ausencia; (iii) el índice del CCME con 2 a 10 variables, 1 a 12 muestreos y parámetros no medidos; y (iv) balance iónico, RAS, dureza calculada e índices de Langelier y Ryznar en todo el rango de salinidad. La verificación compara implementaciones independientes de las mismas definiciones; no valida los valores guía, que se controlaron por transcripción y cotejo de fuentes, ni la interfaz.",
      ]},
      {h: "Ejemplos con datos simulados", p: [
        "Para ilustrar el uso se simularon (semilla 20260923) seis puntos de un sistema altoandino: dos pozos (P1 y P2), dos vertientes salinas (V1 y V2) y un río aguas arriba y aguas abajo (R1 y R2), con 30 parámetros. Para que los datos fueran químicamente coherentes, el bicarbonato se ajustó para cerrar el balance iónico, los SDT se calcularon como suma de iones y la CE, como SDT/0,65. Las seis muestras se evaluaron frente a las 17 normas distintas de la base (sin las cuatro tablas de la Ley 24.585, idénticas a las del Decreto 831/93). Para medir la sensibilidad del índice del CCME al conjunto de variables, se simularon 12 muestreos mensuales de un pozo y se calculó el índice con los objetivos del Código Alimentario Argentino, primero con las 16 variables que tienen objetivo y luego con 500 subconjuntos al azar de 3 a 15 variables. En cada tamaño se registró la proporción de subconjuntos cuyo índice cae en una categoría distinta de la obtenida con las 16 variables.",
      ]},
    ]},
    {h: "RESULTADOS Y DISCUSIÓN", sub: [
      {h: "Verificación", p: [
        "Las conversiones de unidades coincidieron con la implementación independiente con una diferencia relativa máxima de 4,1 × 10⁻¹⁶, las decisiones frente al límite coincidieron en los 1000 casos, y las diferencias máximas fueron de 2,8 × 10⁻¹⁴ en el índice del CCME y sus factores y de 2,5 × 10⁻¹⁵ en los cálculos iónicos (Tabla 2), es decir, diferencias de redondeo de la aritmética de doble precisión. Durante el desarrollo, esta comparación obligó a reemplazar los factores de conversión redondeados que suelen usarse (4,4268 para NO₃⁻/N; 2,497 y 4,118 para la dureza) por cocientes de masas molares, que eliminaron diferencias relativas del orden de 10⁻⁵.",
      ]},
      {h: "Una misma muestra, distintos veredictos", p: [
        "La Tabla 3 compara los límites de agua de consumo de los principales marcos incluidos. El arsénico es el caso de mayor peso sanitario en la región: su origen es geológico y afecta aguas subterráneas de amplias zonas de Argentina y de los Andes [33–35]. Para el arsénico, cinco de los seis coinciden en 0,01 mg/L, y el nivel guía argentino para fuentes que se van a potabilizar es cinco veces mayor. Para el nitrito, los límites expresados en la misma forma difieren en un factor de 25, y para el boro, en un factor de 2,4.",
        "Esa heterogeneidad se traduce en veredictos distintos para una misma muestra (Fig. 2a). El pozo P2, con 1,08 mg/L de boro y 501 mg/L de SDT, cumple en lo medido con el Código Alimentario, la OMS y la Unión Europea; supera sólo el valor secundario de SDT de la EPA; y no cumple con la norma japonesa de agua potable, cuyo límite de boro es 1,0 mg/L, ni con el nivel guía del Decreto 831/93 para fuentes de agua de bebida. El pozo P1, con 27,7 µg/L de arsénico, no cumple con ninguna norma de consumo, y con la japonesa supera además el fluoruro (1,32 frente a 0,8 mg/L). Las vertientes salinas no cumplen con casi ningún marco, salvo la clase industrial 3 japonesa, que sólo considera pH, DBO y oxígeno disuelto. En la figura se aplicaron todas las normas a todas las muestras para mostrar el contraste; en un informe se eligen las que corresponden al uso de cada punto, y Kenti las agrupa por uso.",
        "La Fig. 2b muestra el otro aspecto del problema: con 30 parámetros medidos, un conjunto amplio para un monitoreo de rutina, se evaluó entre el 47 % y el 73 % de los parámetros que fijan las normas nacionales e internacionales de consumo, vida acuática y ganado. Sólo las normas con pocos parámetros (FAO, clases de río y biota japonesas) quedaron cubiertas por completo. En estas condiciones, afirmar que una muestra «cumple» sin más es incorrecto; lo que puede sostenerse es que cumple en los parámetros medidos, con la lista explícita de los faltantes. Esa es la distinción que Kenti hace entre «cumple» y «cumple en lo medido».",
      ]},
      {h: "Sensibilidad del índice del CCME al conjunto de variables", p: [
        "Con las 16 variables, el índice del pozo simulado fue 87,3 (categoría Buena). La media de los subconjuntos se mantuvo cerca de ese valor para todos los tamaños (85,8 a 87,3), pero la dispersión fue grande con pocas variables (Fig. 3): con tres variables, el 95 % central de los valores fue de 52,1 a 100, y el 70 % de los subconjuntos cayó en una categoría distinta de Buena. Con hasta diez variables, la categoría cambió en el 19 % al 71 % de los subconjuntos; con 14 o más, en el 2,4 % o menos. El índice no está sesgado por el número de variables en este ejemplo, pero sí es poco confiable con pocas, y su valor depende de cuáles se incluyan: las que fallan pesan en F₁ en proporción inversa al total. Las revisiones de índices señalan la selección de variables como una de las principales fuentes de incertidumbre [25, 26], y en el índice del CCME se ha discutido su dependencia del número de variables y de muestreos [28, 29].",
        "La consecuencia práctica es que el índice debe informarse junto con el número y la lista de variables, y que sólo deberían compararse índices calculados con el mismo conjunto. Kenti muestra en la tabla del índice las variables y los resultados usados en cada sitio, advierte cuando los conjuntos difieren entre sitios y señala los casos con menos de cuatro variables o muestreos.",
      ]},
      {h: "Limitaciones", p: [
        "Los valores guía son transcripciones y los marcos cambian: la Unión Europea reducirá los límites de cromo y plomo en 2036 [2], la regla de plomo y cobre de la EPA de 2024 prevé bajar el nivel de acción del plomo desde 2027 [3] y Japón convirtió en norma el límite de PFOS y PFOA en 2026 [7]. Cada valor lleva su cita y su nota de vigencia, pero el usuario debe verificar la versión vigente en su jurisdicción. Las tablas de la Ley 24.585 sólo se cotejaron parcialmente contra el texto oficial. La evaluación compara muestras individuales, mientras que varias normas se definen sobre promedios anuales o percentiles; el programa lo indica en la nota del límite, pero no calcula esos estadísticos. No se incluyen compuestos orgánicos volátiles, plaguicidas ni la mayoría de los subproductos de la desinfección. El tratamiento de los valores censurados se limita a reglas de decisión y no incluye métodos estadísticos para estimar medias o percentiles con datos censurados [14, 30, 32]. El ejecutable nativo es sólo para Windows, aunque el mismo código corre en Linux y macOS.",
      ]},
    ]},
    {h: "CONCLUSIONES", p: [
      "Kenti Calidad de Agua evalúa análisis de agua frente a 21 normas de ocho marcos jurisdiccionales o internacionales a la vez, sin exigir un conjunto fijo de parámetros y declarando qué falta. Sus conversiones, decisiones e índices coinciden con una implementación independiente hasta el redondeo de la aritmética de doble precisión. Los ejemplos muestran que la misma muestra puede cumplir con un marco y no con otro por diferencias de límites y de forma de expresión, que ni siquiera un monitoreo amplio cubre todos los parámetros de las normas, y que el índice del CCME calculado con pocas variables puede cambiar de categoría según cuáles se incluyan. Por eso la herramienta privilegia la trazabilidad (la cita, la condición y la forma de cada límite) y la salvedad explícita por sobre un veredicto único. El código es abierto y los datos se guardan en formato abierto, de modo que cualquier resultado puede recalcularse fuera del programa.",
    ]},
    {h: "DISPONIBILIDAD DEL SOFTWARE Y DE LOS DATOS", p: [
      "El código fuente de Kenti Calidad de Agua 0.2 (interfaz, cálculos y lanzador), la base de niveles guía en formato CSV (Tabla S1), los datos simulados, los guiones de verificación de la Tabla 2 y los que generan las Figuras 2 y 3 se publican bajo licencia MIT en https://github.com/carlosmariaflores-cloud/kenti-calidad-agua (versión 0.2 archivada en Zenodo, doi:10.5281/zenodo.22938332). Todo se reproduce con un único guion (reproducir.sh), de acuerdo con los principios FAIR para software de investigación [45]. El nombre y el logo de Kenti están excluidos de la licencia.",
    ]},
    {h: "AGRADECIMIENTOS", p: [
      "Agradezco a Mariana Urueña por su participación en el desarrollo de Kenti, y a Rafael Silva, gerente de Branlap S.A., y a Hugo San Martín, de Aptico, por su constante apoyo. Este trabajo no recibió financiamiento específico.",
    ]},
    {h: "CONFLICTO DE INTERESES", p: [
      "El autor es desarrollador de Kenti. El módulo descrito se publica con código abierto; el autor ofrece servicios de consultoría ambiental y módulos especializados de Kenti con bases de referencia.",
    ]},
  ],
  referencias: [
    "World Health Organization: Guidelines for Drinking-water Quality: Fourth Edition Incorporating the First and Second Addenda. World Health Organization, Geneva, Switzerland, 2022.",
    "European Parliament and Council of the European Union: Directive (EU) 2020/2184 of 16 December 2020 on the quality of water intended for human consumption. Official Journal of the European Union, L 435, 1–62, 2020.",
    "U.S. Environmental Protection Agency: National Primary Drinking Water Regulations (40 CFR Part 141) and National Secondary Drinking Water Regulations (40 CFR Part 143). https://www.epa.gov/ground-water-and-drinking-water/national-primary-drinking-water-regulations [consultado en septiembre de 2026]",
    "República Argentina: Código Alimentario Argentino, Capítulo XII, artículo 982, texto según Resolución Conjunta SCS–SAByDR 33/2023. https://www.argentina.gob.ar/anmat/codigoalimentario [consultado en septiembre de 2026]",
    "República Argentina: Decreto 831/1993, reglamentario de la Ley 24.051 de Residuos Peligrosos, Anexo II: Niveles guía de calidad de agua. Boletín Oficial, 1993. [en español]",
    "República Argentina: Ley 24.585 de Protección Ambiental para la Actividad Minera (Código de Minería), Anexo IV. Boletín Oficial, 1995. [en español]",
    "Ministry of the Environment, Japan: Drinking water quality standards (水質基準項目と基準値, 52 items), in force from 1 April 2026. https://www.env.go.jp/water/water_supply/kijun/kijunchi.html [consultado en septiembre de 2026] [en japonés]",
    "Ministry of the Environment, Japan: Environmental quality standards for water pollution (水質汚濁に係る環境基準), Tables 1 and 2. https://www.env.go.jp/kijun/wt2-1-1.html [consultado en septiembre de 2026] [en japonés]",
    "Agriculture, Forestry and Fisheries Research Council, Japan: Agricultural (paddy rice) water quality standard (農業（水稲）用水基準), 4 October 1971. [en japonés]",
    "Canadian Council of Ministers of the Environment: Canadian Water Quality Guidelines for the Protection of Agricultural Water Uses: Livestock Water. Canadian Environmental Quality Guidelines, CCME, Winnipeg, Canada.",
    "ANZECC, ARMCANZ: Australian and New Zealand Guidelines for Fresh and Marine Water Quality, Chapter 4.3: Livestock Drinking Water Quality. Australian and New Zealand Environment and Conservation Council and Agriculture and Resource Management Council of Australia and New Zealand, Canberra, Australia, 2000.",
    "Ayers RS, Westcot DW: Water Quality for Agriculture. FAO Irrigation and Drainage Paper 29 Rev. 1, Food and Agriculture Organization of the United Nations, Rome, Italy, 1985.",
    "Panko RR: What we don't know about spreadsheet errors today: the facts, why we don't believe them, and what we need to do. Proceedings of the EuSpRIG 2015 Conference «Spreadsheet Risk Management», European Spreadsheet Risks Interest Group, pp. 79–93, 2015. doi:10.48550/arXiv.1602.02601",
    "Helsel DR: Statistics for Censored Environmental Data Using Minitab and R. 2nd ed., John Wiley & Sons, Hoboken, USA, 2012.",
    "Canadian Council of Ministers of the Environment: Canadian Water Quality Guidelines for the Protection of Aquatic Life: CCME Water Quality Index, User's Manual — 2017 Update. CCME, Winnipeg, Canada, 2017.",
    "Lumb A, Sharma TC, Bibeault J-F: A review of genesis and evolution of water quality index (WQI) and some future directions. Water Qual. Expo. Health, 3(1), 11–24, 2011. doi:10.1007/s12403-011-0040-0",
    "APHA, AWWA, WEF: Standard Methods for the Examination of Water and Wastewater. 24th ed., American Public Health Association, Washington, DC, USA, 2023.",
    "Richards LA (ed.): Diagnosis and Improvement of Saline and Alkali Soils. Agriculture Handbook No. 60, United States Department of Agriculture, Washington, DC, USA, 1954.",
    "Langelier WF: The analytical control of anti-corrosion water treatment. J. Am. Water Works Assoc., 28(10), 1500–1521, 1936.",
    "Ryznar JW: A new index for determining amount of calcium carbonate scale formed by a water. J. Am. Water Works Assoc., 36(4), 472–483, 1944.",
    "Harris CR, Millman KJ, van der Walt SJ, et al.: Array programming with NumPy. Nature, 585, 357–362, 2020. doi:10.1038/s41586-020-2649-2",
    "Flores CM, Urueña M: Kenti Libre: cálculo de índices ecológicos para datos de monitoreo, versión 0.3.1. Zenodo, 2026. doi:10.5281/zenodo.22882918",
    "Prohaska T, Irrgeher J, Benefield J, et al.: Standard atomic weights of the elements 2021 (IUPAC Technical Report). Pure Appl. Chem., 94(5), 573–600, 2022. doi:10.1515/pac-2019-0603",
    "Horton RK: An index number system for rating water quality. J. Water Pollut. Control Fed., 37(3), 300–306, 1965.",
    "Sutadian AD, Muttil N, Yilmaz AG, Perera BJC: Development of river water quality indices—a review. Environ. Monit. Assess., 188(1), 58, 2016. doi:10.1007/s10661-015-5050-0",
    "Uddin MG, Nash S, Olbert AI: A review of water quality index models and their use for assessing surface water quality. Ecol. Indic., 122, 107218, 2021. doi:10.1016/j.ecolind.2020.107218",
    "Swamee PK, Tyagi A: Describing water quality with aggregate index. J. Environ. Eng., 126(5), 451–455, 2000. doi:10.1061/(ASCE)0733-9372(2000)126:5(451)",
    "Lumb A, Halliwell D, Sharma T: Application of CCME Water Quality Index to monitor water quality: a case study of the Mackenzie River Basin, Canada. Environ. Monit. Assess., 113(1–3), 411–429, 2006. doi:10.1007/s10661-005-9092-6",
    "Hurley T, Sadiq R, Mazumder A: Adaptation and evaluation of the Canadian Council of Ministers of the Environment Water Quality Index (CCME WQI) for use as an effective tool to characterize drinking source water quality. Water Res., 46(11), 3544–3552, 2012. doi:10.1016/j.watres.2012.03.061",
    "Gilliom RJ, Helsel DR: Estimation of distributional parameters for censored trace level water quality data: 1. Estimation techniques. Water Resour. Res., 22(2), 135–146, 1986. doi:10.1029/WR022i002p00135",
    "Helsel DR: More than obvious: better methods for interpreting nondetect data. Environ. Sci. Technol., 39(20), 419A–423A, 2005. doi:10.1021/es053368a",
    "Antweiler RC, Taylor HE: Evaluation of statistical treatments of left-censored environmental data using coincident uncensored data sets: I. Summary statistics. Environ. Sci. Technol., 42(10), 3732–3738, 2008. doi:10.1021/es071301c",
    "Smedley PL, Kinniburgh DG: A review of the source, behaviour and distribution of arsenic in natural waters. Appl. Geochem., 17(5), 517–568, 2002. doi:10.1016/S0883-2927(02)00018-5",
    "Bundschuh J, Litter MI, Parvez F, et al.: One century of arsenic exposure in Latin America: a review of history and occurrence from 14 countries. Sci. Total Environ., 429, 2–35, 2012. doi:10.1016/j.scitotenv.2011.06.024",
    "Litter MI, Ingallinella AM, Olmos V, et al.: Arsenic in Argentina: occurrence, human health, legislation and determination. Sci. Total Environ., 676, 756–766, 2019. doi:10.1016/j.scitotenv.2019.04.262",
    "Flexer V, Baspineiro CF, Galli CI: Lithium recovery from brines: a vital raw material for green energies with a potential environmental impact in its mining and processing. Sci. Total Environ., 639, 1188–1204, 2018. doi:10.1016/j.scitotenv.2018.05.223",
    "Ward MH, Jones RR, Brender JD, et al.: Drinking water nitrate and human health: an updated review. Int. J. Environ. Res. Public Health, 15(7), 1557, 2018. doi:10.3390/ijerph15071557",
    "Hem JD: Study and Interpretation of the Chemical Characteristics of Natural Water. 3rd ed., U.S. Geological Survey Water-Supply Paper 2254, Alexandria, USA, 1985. doi:10.3133/wsp2254",
    "Hayashi M: Temperature-electrical conductivity relation of water for environmental monitoring and geophysical data inversion. Environ. Monit. Assess., 96(1–3), 119–128, 2004. doi:10.1023/B:EMAS.0000031719.83065.68",
    "Walton NRG: Electrical conductivity and total dissolved solids—what is their precise relationship? Desalination, 72(3), 275–292, 1989. doi:10.1016/0011-9164(89)80012-8",
    "Fritz SJ: A survey of charge-balance errors on published analyses of potable ground and surface waters. Ground Water, 32(4), 539–546, 1994. doi:10.1111/j.1745-6584.1994.tb00888.x",
    "Wilson G, Aruliah DA, Brown CT, et al.: Best practices for scientific computing. PLoS Biol., 12(1), e1001745, 2014. doi:10.1371/journal.pbio.1001745",
    "Ziemann M, Eren Y, El-Osta A: Gene name errors are widespread in the scientific literature. Genome Biol., 17, 177, 2016. doi:10.1186/s13059-016-1044-7",
    "Sandve GK, Nekrutenko A, Taylor J, Hovig E: Ten simple rules for reproducible computational research. PLoS Comput. Biol., 9(10), e1003285, 2013. doi:10.1371/journal.pcbi.1003285",
    "Lamprecht A-L, Garcia L, Kuzak M, et al.: Towards FAIR principles for research software. Data Sci., 3(1), 37–59, 2020. doi:10.3233/DS-190026",
    "Parkhurst DL, Appelo CAJ: Description of Input and Examples for PHREEQC Version 3—A Computer Program for Speciation, Batch-Reaction, One-Dimensional Transport, and Inverse Geochemical Calculations. U.S. Geological Survey Techniques and Methods, Book 6, Chapter A43, Denver, USA, 2013. doi:10.3133/tm6A43",
    "Yang J, Liu H, Tang Z, Peeters L, Ye M: Visualization of aqueous geochemical data using Python and WQChartPy. Groundwater, 60(4), 555–564, 2022. doi:10.1111/gwat.13185",
  ],
};
