// Manuscript for the Journal of Water and Environment Technology (JWET), English version.
// Markup: *italic*, **bold**. References are numbered by order of first appearance.
module.exports = {
  titulo: "Kenti Water Quality: an open-source tool for assessing water analyses against multiple regulatory frameworks with incomplete data",
  autores: "Carlos María Flores",
  afiliacion: "Atoj S.A.S., Tafí Viejo, Tucumán, Argentina",
  palabras: "Keywords: water quality; guideline values; water quality index; censored data; open-source software",
  correspondencia: [
    "Corresponding author: Carlos María Flores",
    "Address: Lomalinda J6, Tafí Viejo, Tucumán, Argentina",
    "Telephone: +54 381 647 0001",
    "E-mail: carlosmaria.flores@gmail.com",
    "ORCID: 0009-0000-8959-4738",
  ],
  resumen: "Water quality reports compare laboratory results with guideline values from regulatory frameworks that differ in units, chemical form of expression, conditional limits and required parameters, often with incomplete or censored data. We present Kenti Water Quality, an open-source local application that reads heterogeneous laboratory reports, converts 63 units to a canonical unit using molar masses, density and molality, and assesses each sample against 21 frameworks from Argentina, Japan, the WHO, the European Union, the United States, Canada, Australia and New Zealand, and the FAO. No parameter is mandatory: missing parameters and results made inconclusive by the detection limit are reported as caveats. The tool also computes the CCME water quality index, ion balance, sodium adsorption ratio and Langelier index. Against an independent Python implementation, with 1000 simulated cases per procedure, maximum differences were 4.1 × 10⁻¹⁶ (relative) for unit conversions and 2.8 × 10⁻¹⁴ for the index, and all decisions agreed. With simulated data, the index computed from three variables fell in a different category from the 16-variable index in 70% of subsets.",
  secciones: [
    {h: "INTRODUCTION", p: [
      "Water quality assessment in environmental impact studies, baseline surveys and monitoring programmes almost always ends in a comparison: each laboratory result against the guideline value that applies to the intended use of the water. In practice there is rarely a single frame of reference. The same report may have to answer to the national standard, to the World Health Organization (WHO) guidelines required by lenders and corporate standards, and to specific standards for irrigation, livestock watering or the protection of aquatic life [1–12].",
      "These frameworks are not interchangeable. Nitrate, whose guideline value is based on infant methaemoglobinaemia [1, 37], is limited to 50 mg/L expressed as the NO₃⁻ ion by the WHO and the European Union [1, 2], but to 10 mg/L expressed as nitrogen in the United States and Japan [3, 7], that is, 44.3 mg/L as NO₃⁻; the Argentine Food Code sets 45 mg/L [4]. Boron is allowed up to 2.4 mg/L by the WHO and, since 2023, in Argentina, 1.5 mg/L in the European Union and 1.0 mg/L in Japan [1, 2, 4, 7]. Some limits depend on the sample or the site: those for cadmium, copper, nickel and lead for aquatic life in Argentine Decree 831/93 change with water hardness [5], and the Argentine Food Code fluoride limit changes with the mean annual temperature of the site [4]. In addition, each framework distinguishes health-based values from acceptability, indicator or secondary values, which do not carry the same weight in a diagnosis.",
      "The data, in turn, are rarely complete. Each laboratory reports a different set of parameters, in different units (mg/L, µg/L, meq/L, ppm, or molality in the brines of high-Andean salt flats [36]), whose equivalence depends on molar mass, charge and density [38], and with values censored by the detection limit (“<0.005”, “ND”), which require explicit rules: substituting half the limit or zero can bias statistics [14, 30–32]. Field meters report conductivity sometimes compensated to 25 °C and sometimes not, and conductivity changes by about 2% per degree [39]. All this is usually handled in spreadsheets, where formula and transcription errors are frequent and persist even in the published literature [13, 43].",
      "Water quality indices summarise the comparison in a single number; since the index proposed by Horton [24], dozens have been developed, with different approaches to variable selection, normalisation, weighting and aggregation [16, 25, 26], and all face eclipsing and ambiguity problems when aggregating [27]. The index of the Canadian Council of Ministers of the Environment (CCME) is widely used because it accepts any set of variables and any set of objectives [15, 16, 28, 29]. This flexibility has a cost that is rarely discussed in practice: the value depends on which variables were included, and two sites or two surveys with different variable sets are not directly comparable.",
      "Widely used open tools exist for speciation and saturation indices, such as PHREEQC [46], or for hydrochemical diagrams, such as WQChartPy [47], but they are not designed to compare a sample with several regulatory frameworks at once or to declare which parameters are missing for each.",
      "This paper presents Kenti Water Quality, an open-source module of Kenti [22] designed around four principles: (i) no parameter is mandatory, but every missing parameter is declared; (ii) every limit is traceable to its source, with its scale (national, regional or international) and its type; (iii) conversions and decisions are explicit and reproducible, offline and with data in an open format; and (iv) every calculation is verified against an independent implementation, following recommended practices for scientific software [42, 44, 45]. We describe the design, the decision rules and the numerical verification, and illustrate two practical consequences with simulated data: the heterogeneity of verdicts across frameworks for the same sample, and the sensitivity of the CCME index to the subset of measured variables.",
    ]},
    {h: "MATERIALS AND METHODS", sub: [
      {h: "Architecture", p: [
        "Kenti Water Quality uses the same launcher as the other Kenti modules [22]: an executable written in Go 1.24, using only the standard library, that starts an HTTP server at the local address 127.0.0.1 and opens the interface in an Edge or Chrome window. The interface and all calculations are written in HTML, CSS and JavaScript embedded in the executable; data never leave the computer and are stored in a human-readable JSON file with automatic backup. Arithmetic is double precision (IEEE 754). The interface is available in Spanish or English, at the user’s choice; the language changes texts, parameter and standard names and number formatting, but not the data or the calculations. The program has seven tabs: data, regulatory assessment, water quality index, ions and derived quantities, unit converter, checks and frameworks (Fig. 1). Results are exported to an Excel workbook with the original data, the converted data, the assessment of each parameter against each framework, the caveats, the index, the derived calculations, the checks and the table of guideline values used, with its citation.",
      ]},
      {h: "Data input", p: [
        "The program accepts tables pasted from a spreadsheet or .xlsx files in two layouts: one sample per row, or the usual laboratory report layout, with parameters in rows and samples in columns. The layout is detected by comparing how many parameter names are recognised in the best row and in the best column of the table. Headers are recognised with regular expressions on normalised text (without accents or capitals), using the name, chemical symbol or usual abbreviations in Spanish and English. The unit is read from the header itself, from a row of units or from a “Unit” column; the chemical form (“as N”, “NO₃-N”), the fraction (total or dissolved) and a detection-limit column are also read. Rows and columns containing guideline values, methods or averages are discarded.",
        "Each column declares its decimal separator (comma or point), detected from all its values. Values are classified as numeric, below the detection limit (“<0.005”, or “ND” with the column’s limit), greater than a value (“>2400”), absence or presence (for microbiology), and no data (“n/a”, “–”, empty cell). Values that cannot be read are flagged as errors and are not assessed.",
      ]},
      {h: "Units and chemical forms", p: [
        "Each parameter has a canonical unit: mg/L of the usual ionic or elemental form for concentrations, µS/cm for electrical conductivity (EC), °C for temperature, mg/L as CaCO₃ for hardness and alkalinity, and CFU/100 mL for bacterial indicators. The program recognises 63 units in 13 families. For concentrations, the conversion of a value *x* to mg/L of the canonical form, with molar mass *M* and charge *z*, follows the definitions [38]:",
      ], eq: [
        "mass per volume (mg/L, µg/L, g/L, % w/v):   C = f · x · M / M_form",
        "mass per mass (ppm, ppb, mg/kg, % w/w):   C = f · x · ρ · M / M_form",
        "molar (mol/L, mmol/L, µmol/L):   C = f · x · M · 1000",
        "molal (mol/kg, mmol/kg):   C = f · x · M · 1000 · (ρ · 10⁶ − TDS) / 10⁶",
        "equivalents (meq/L, µeq/L):   C = f · x · (M / z) · 1000",
      ], p2: [
        "where *f* is the unit factor, *M*<sub>form</sub> is the molar mass of the form in which the value was expressed (for example, 14.007 g/mol if nitrate was reported as N), ρ is the sample density in g/mL and TDS is total dissolved solids in mg/L. Molar masses are those of IUPAC [23]. If density is missing, 1 g/mL is used and a warning is issued; the warning is stronger if TDS exceeds 10 g/L or EC exceeds 15 mS/cm, because in brines (1.1 to 1.25 g/mL) the difference between ppm and mg/L exceeds 10%. Resistivity is converted as the inverse of conductivity, and uncompensated EC can be brought to 25 °C with the linear correction EC<sub>25</sub> = EC<sub>*t*</sub> / [1 + α (*t* − 25)], with α = 2%/°C by default and user-configurable [17, 39]. The same functions feed a converter for single values.",
      ]},
      {h: "Guideline value database", p: [
        "The database includes 21 frameworks with 373 guideline values (Table 1), transcribed from the official texts or, when this was not possible, cross-checked against at least two secondary sources [1–12]. For Japan, we included the drinking water quality standards in force since 1 April 2026 (52 items, of which Kenti includes the inorganic, general and microbiological items) [7], the environmental quality standards for human health and for the living environment of rivers by use class [8], and the agricultural water standard for paddy rice [9]. The tables of Annex IV of Law 24.585, which governs mining in Argentina, were loaded with the values of Decree 831/93 from which they derive [5, 6], as separate frameworks so that the report cites the applicable one.",
        "Each guideline value carries its chemical form of expression, its type (health-based, acceptability, indicator, secondary, action level, operational or degree of restriction) and a note with its conditions of application. Conditional limits are resolved for each sample: measured hardness or, if missing, hardness calculated from calcium and magnesium, for the metals of Table 2 of Decree 831/93 [5]; pH, calcium and dissolved organic carbon for aluminium in that table; the site’s mean annual temperature for the Argentine Food Code fluoride limit [4]; the livestock species for copper and dissolved solids in livestock water [10, 11]; and the river class for the Japanese standards [8]. If the datum that conditions the limit is missing, the most stringent value is used and declared as a caveat.",
        "Transcription revealed an inconsistency that Kenti makes visible rather than correcting: Table 6 of Decree 831/93 sets 50 µg/L of zinc for livestock watering, whereas the source it cites sets 50 mg/L. The program compares against the printed value and flags it in the note of the limit.",
      ]},
      {h: "Decision rules", p: [
        "Each sample–parameter pair is classified against each limit into one of six states: complies, exceeds, slight-to-moderate or severe restriction (only for the FAO irrigation guidelines, which use two thresholds [12]), inconclusive, and no data. A numeric value exceeds if it is greater than the maximum or less than the minimum; a value equal to the limit complies. A value below the detection limit (DL) complies if the DL does not exceed the maximum, and is inconclusive otherwise; against a minimum, it exceeds if the DL does not reach the minimum. A value reported as “greater than *x*” exceeds only if *x* already reaches the maximum. The presence of a bacterial indicator exceeds an absence limit. For frameworks that limit the sum of nitrate and nitrite as N [7, 10], the sum is computed from the available values and values below the DL count as zero, which is declared.",
        "Each sample receives one verdict per framework: “complies” if all parameters of the framework were assessed and all comply; “complies for measured parameters” if everything assessed complies but parameters are missing or results are inconclusive; “exceeds non-health values” if only acceptability, indicator, secondary or operational values are exceeded, or there is slight restriction; and “does not comply” if a health-based value is exceeded or there is severe restriction. Caveats are generated with the verdict: how many parameters of the framework were assessed and which are missing, which parameters decisive for the use were not measured (for example, microbiology in drinking water), which results are inconclusive and why, which conditions were assumed, which values were calculated instead of measured, and which conversions used an assumed density. The program also drafts a results paragraph for the report.",
      ]},
      {h: "Water quality index and derived calculations", p: [
        "The CCME index [15] is computed per site and for the whole set of samples, with the objectives of the chosen framework resolved for each sample:",
      ], eq: [
        "F₁ = 100 · (failed variables) / (assessed variables)",
        "F₂ = 100 · (failed results) / (assessed results)",
        "excursion = value / objective − 1 (maxima) or objective / value − 1 (minima);   nse = Σ excursions / assessed results",
        "F₃ = nse / (0.01 · nse + 0.01);   WQI = 100 − √(F₁² + F₂² + F₃²) / 1.732",
      ], p2: [
        "Inconclusive results and bacterial indicators with an absence objective are excluded, because the excursion is undefined for a zero objective; both are reported. The program warns when there are fewer than four variables or four sampling events, as the manual recommends [15], and when the sites being compared do not share the same set of variables.",
        "From the major ions, the program computes the ion balance with the acceptance criteria of APHA 1030 E [17, 41], the hydrochemical facies, calculated hardness, the sodium adsorption ratio (SAR), the Riverside class [18], the FAO infiltration restriction by SAR and EC [12], the Langelier [19] and Ryznar [20] indices, and the WHO and European Union rule [nitrate]/50 + [nitrite]/3 ≤ 1 [1, 2]. These calculations also feed the data quality checks: ion balance outside the criterion, TDS/EC ratio outside 0.55–0.75 [38, 40], disagreement between measured and calculated hardness, dissolved fraction greater than total, negative or out-of-range values, probably wrong units, and numbers made ambiguous by the thousands separator.",
      ]},
      {h: "Numerical verification", p: [
        "The calculation functions were run unmodified in Node.js on 1000 simulated cases per procedure (seed 20260923), and their results were compared with an independent implementation in Python and NumPy [21, 42], written from the definitions and not from the Kenti code. The cases covered: (i) conversions of 15 parameters among 20 concentration units, with N and P forms, densities from 0.998 to 1.25 g/mL and TDS up to 350 g/L; (ii) decisions against maxima, minima, ranges and degrees of restriction, with numeric values, values below the DL, values greater than a value and presence, including absence objectives; (iii) the CCME index with 2 to 10 variables, 1 to 12 sampling events and unmeasured parameters; and (iv) ion balance, SAR, calculated hardness and the Langelier and Ryznar indices over the whole salinity range. The verification compares independent implementations of the same definitions; it does not validate the guideline values, which were checked by transcription and cross-checking of sources, nor the interface.",
      ]},
      {h: "Examples with simulated data", p: [
        "To illustrate its use, we simulated (seed 20260923) six points of a high-Andean system: two wells (P1 and P2), two saline springs (V1 and V2) and a river upstream and downstream (R1 and R2), with 30 parameters. To make the data chemically consistent, bicarbonate was adjusted to close the ion balance, TDS was computed as the sum of ions and EC as TDS/0.65. The six samples were assessed against the 17 distinct frameworks of the database (excluding the four tables of Law 24.585, identical to those of Decree 831/93). To measure the sensitivity of the CCME index to the set of variables, we simulated 12 monthly sampling events of a well and computed the index with the objectives of the Argentine Food Code, first with the 16 variables that have an objective and then with 500 random subsets of 3 to 15 variables. For each subset size, we recorded the proportion of subsets whose index fell in a category different from that obtained with the 16 variables.",
      ]},
    ]},
    {h: "RESULTS AND DISCUSSION", sub: [
      {h: "Verification", p: [
        "Unit conversions agreed with the independent implementation with a maximum relative difference of 4.1 × 10⁻¹⁶, decisions against the limit agreed in all 1000 cases, and the maximum differences were 2.8 × 10⁻¹⁴ for the CCME index and its factors and 2.5 × 10⁻¹⁵ for the ionic calculations (Table 2), that is, rounding differences of double-precision arithmetic. During development, this comparison forced us to replace the rounded conversion factors commonly used (4.4268 for NO₃⁻/N; 2.497 and 4.118 for hardness) with ratios of molar masses, which removed relative differences of the order of 10⁻⁵.",
      ]},
      {h: "Same sample, different verdicts", p: [
        "Table 3 compares the drinking water limits of the main frameworks included. Arsenic is the most important case for health in the region: it is of geological origin and affects groundwater across large areas of Argentina and the Andes [33–35]. For arsenic, five of the six frameworks agree on 0.01 mg/L, and the Argentine guideline value for sources to be treated for drinking is five times higher. For nitrite, limits expressed in the same form differ by a factor of 25, and for boron by a factor of 2.4.",
        "This heterogeneity translates into different verdicts for the same sample (Fig. 2a). Well P2, with 1.08 mg/L boron and 501 mg/L TDS, complies for measured parameters with the Argentine Food Code, the WHO and the European Union; exceeds only the EPA secondary value for TDS; and does not comply with the Japanese drinking water standard, whose boron limit is 1.0 mg/L, nor with the Decree 831/93 guideline value for drinking water sources. Well P1, with 27.7 µg/L arsenic, does not comply with any drinking water framework, and under the Japanese standard it also exceeds fluoride (1.32 vs. 0.8 mg/L). The saline springs fail almost every framework, except the Japanese industrial class 3, which considers only pH, BOD and dissolved oxygen. In the figure, all frameworks were applied to all samples to show the contrast; in a report, only those that correspond to the use of each point are chosen, and Kenti groups them by use.",
        "Fig. 2b shows the other side of the problem: with 30 measured parameters, a broad set for routine monitoring, between 47% and 73% of the parameters set by the national and international drinking water, aquatic life and livestock frameworks were assessed. Only frameworks with few parameters (FAO, and the Japanese river classes and biota standard) were fully covered. Under these conditions, stating that a sample simply “complies” is incorrect; what can be supported is that it complies for the measured parameters, with an explicit list of those missing. This is the distinction Kenti makes between “complies” and “complies for measured parameters”.",
      ]},
      {h: "Sensitivity of the CCME index to the set of variables", p: [
        "With the 16 variables, the index of the simulated well was 87.3 (Good category). The mean of the subsets remained close to that value for all sizes (85.8 to 87.3), but the spread was large with few variables (Fig. 3): with three variables, the central 95% of values ranged from 52.1 to 100, and 70% of the subsets fell in a category other than Good. With up to ten variables, the category changed in 19% to 71% of the subsets; with 14 or more, in 2.4% or fewer. In this example the index is not biased by the number of variables, but it is unreliable with few variables, and its value depends on which ones are included: failing variables weigh on F₁ in inverse proportion to the total. Reviews of water quality indices identify variable selection as one of the main sources of uncertainty [25, 26], and the dependence of the CCME index on the number of variables and sampling events has been discussed [28, 29].",
        "The practical consequence is that the index should be reported together with the number and list of variables, and that only indices computed with the same set should be compared. Kenti shows the variables and results used for each site in the index table, warns when the sets differ between sites, and flags cases with fewer than four variables or sampling events.",
      ]},
      {h: "Limitations", p: [
        "Guideline values are transcriptions, and frameworks change: the European Union will lower the chromium and lead limits in 2036 [2], the 2024 EPA lead and copper rule plans to lower the lead action level from 2027 [3], and Japan made its PFOS and PFOA limit a standard in 2026 [7]. Each value carries its citation and a note on its validity, but users must check the version in force in their jurisdiction. The tables of Law 24.585 were only partially cross-checked against the official text. The assessment compares individual samples, whereas several frameworks are defined on annual means or percentiles; the program indicates this in the note of the limit but does not compute those statistics. Volatile organic compounds, pesticides and most disinfection by-products are not included. The treatment of censored values is limited to decision rules and does not include statistical methods for estimating means or percentiles from censored data [14, 30, 32]. The native executable is for Windows only, although the same code runs on Linux and macOS.",
      ]},
    ]},
    {h: "CONCLUSIONS", p: [
      "Kenti Water Quality assesses water analyses against 21 frameworks from eight jurisdictional or international sources at once, without requiring a fixed set of parameters and declaring what is missing. Its conversions, decisions and indices agree with an independent implementation to within double-precision rounding. The examples show that the same sample can comply with one framework and not with another because of differences in limits and forms of expression, that even broad monitoring does not cover all the parameters of the frameworks, and that a CCME index computed from few variables can change category depending on which are included. The tool therefore favours traceability (the citation, condition and form of each limit) and explicit caveats over a single verdict. The code is open and data are stored in an open format, so any result can be recomputed outside the program.",
    ]},
    {h: "SOFTWARE AND DATA AVAILABILITY", p: [
      "The source code of Kenti Water Quality 0.2 (interface, calculations and launcher), the guideline value database in CSV format (Table S1), the simulated data, the verification scripts for Table 2 and the scripts that generate Figs. 2 and 3 are released under the MIT license at https://github.com/carlosmariaflores-cloud/kenti-calidad-agua (version 0.2 archived in Zenodo, doi:10.5281/zenodo.22938332). Everything is reproduced with a single script (reproducir.sh), in line with the FAIR principles for research software [45]. The Kenti name and logo are excluded from the license.",
    ]},
    {h: "ACKNOWLEDGEMENTS", p: [
      "I thank Mariana Urueña for her participation in the development of Kenti, and Rafael Silva, manager of Branlap S.A., and Hugo San Martín, of Aptico, for their constant support. This work received no specific funding.",
    ]},
    {h: "CONFLICTS OF INTEREST", p: [
      "The author is the developer of Kenti. The module described is released as open source; the author provides environmental consulting services and specialised Kenti modules with reference databases.",
    ]},
  ],
  referencias: [
    "World Health Organization: Guidelines for Drinking-water Quality: Fourth Edition Incorporating the First and Second Addenda. World Health Organization, Geneva, Switzerland, 2022.",
    "European Parliament and Council of the European Union: Directive (EU) 2020/2184 of 16 December 2020 on the quality of water intended for human consumption. Official Journal of the European Union, L 435, 1–62, 2020.",
    "U.S. Environmental Protection Agency: National Primary Drinking Water Regulations (40 CFR Part 141) and National Secondary Drinking Water Regulations (40 CFR Part 143). https://www.epa.gov/ground-water-and-drinking-water/national-primary-drinking-water-regulations [accessed in September, 2026]",
    "Argentine Republic: Código Alimentario Argentino, Chapter XII, Article 982, as amended by Joint Resolution SCS–SAByDR 33/2023. https://www.argentina.gob.ar/anmat/codigoalimentario [accessed in September, 2026] [in Spanish]",
    "Argentine Republic: Decree 831/1993, regulating Law 24.051 on Hazardous Waste, Annex II: Water quality guideline levels. Boletín Oficial, 1993. [in Spanish]",
    "Argentine Republic: Law 24.585 on Environmental Protection for Mining Activities (Mining Code), Annex IV. Boletín Oficial, 1995. [in Spanish]",
    "Ministry of the Environment, Japan: Drinking water quality standards (水質基準項目と基準値, 52 items), in force from 1 April 2026. https://www.env.go.jp/water/water_supply/kijun/kijunchi.html [accessed in September, 2026] [in Japanese]",
    "Ministry of the Environment, Japan: Environmental quality standards for water pollution (水質汚濁に係る環境基準), Tables 1 and 2. https://www.env.go.jp/kijun/wt2-1-1.html [accessed in September, 2026] [in Japanese]",
    "Agriculture, Forestry and Fisheries Research Council, Japan: Agricultural (paddy rice) water quality standard (農業（水稲）用水基準), 4 October 1971. [in Japanese]",
    "Canadian Council of Ministers of the Environment: Canadian Water Quality Guidelines for the Protection of Agricultural Water Uses: Livestock Water. Canadian Environmental Quality Guidelines, CCME, Winnipeg, Canada.",
    "ANZECC, ARMCANZ: Australian and New Zealand Guidelines for Fresh and Marine Water Quality, Chapter 4.3: Livestock Drinking Water Quality. Australian and New Zealand Environment and Conservation Council and Agriculture and Resource Management Council of Australia and New Zealand, Canberra, Australia, 2000.",
    "Ayers RS, Westcot DW: Water Quality for Agriculture. FAO Irrigation and Drainage Paper 29 Rev. 1, Food and Agriculture Organization of the United Nations, Rome, Italy, 1985.",
    "Panko RR: What we don't know about spreadsheet errors today: the facts, why we don't believe them, and what we need to do. Proceedings of the EuSpRIG 2015 Conference “Spreadsheet Risk Management”, European Spreadsheet Risks Interest Group, pp. 79–93, 2015. doi:10.48550/arXiv.1602.02601",
    "Helsel DR: Statistics for Censored Environmental Data Using Minitab and R. 2nd ed., John Wiley & Sons, Hoboken, USA, 2012.",
    "Canadian Council of Ministers of the Environment: Canadian Water Quality Guidelines for the Protection of Aquatic Life: CCME Water Quality Index, User's Manual — 2017 Update. CCME, Winnipeg, Canada, 2017.",
    "Lumb A, Sharma TC, Bibeault J-F: A review of genesis and evolution of water quality index (WQI) and some future directions. Water Qual. Expo. Health, 3(1), 11–24, 2011. doi:10.1007/s12403-011-0040-0",
    "APHA, AWWA, WEF: Standard Methods for the Examination of Water and Wastewater. 24th ed., American Public Health Association, Washington, DC, USA, 2023.",
    "Richards LA (ed.): Diagnosis and Improvement of Saline and Alkali Soils. Agriculture Handbook No. 60, United States Department of Agriculture, Washington, DC, USA, 1954.",
    "Langelier WF: The analytical control of anti-corrosion water treatment. J. Am. Water Works Assoc., 28(10), 1500–1521, 1936.",
    "Ryznar JW: A new index for determining amount of calcium carbonate scale formed by a water. J. Am. Water Works Assoc., 36(4), 472–483, 1944.",
    "Harris CR, Millman KJ, van der Walt SJ, et al.: Array programming with NumPy. Nature, 585, 357–362, 2020. doi:10.1038/s41586-020-2649-2",
    "Flores CM, Urueña M: Kenti Libre: cálculo de índices ecológicos para datos de monitoreo, versión 0.3.1 [Kenti Libre: computing ecological indices for monitoring data, version 0.3.1]. Zenodo, 2026. doi:10.5281/zenodo.22882918 [in Spanish]",
    "Prohaska T, Irrgeher J, Benefield J, et al.: Standard atomic weights of the elements 2021 (IUPAC Technical Report). Pure Appl. Chem., 94(5), 573–600, 2022. doi:10.1515/pac-2019-0603",
    "Horton RK: An index number system for rating water quality. J. Water Pollut. Control Fed., 37(3), 300–306, 1965.",
    "Sutadian AD, Muttil N, Yilmaz AG, Perera BJC: Development of river water quality indices—a review. Environ. Monit. Assess., 188(1), 58, 2016. doi:10.1007/s10661-015-5050-0",
    "Uddin MG, Nash S, Olbert AI: A review of water quality index models and their use for assessing surface water quality. Ecol. Indic., 122, 107218, 2021. doi:10.1016/j.ecolind.2020.107218",
    "Swamee PK, Tyagi A: Describing water quality with aggregate index. J. Environ. Eng., 126(5), 451–455, 2000. doi:10.1061/(ASCE)0733-9372(2000)126:5(451)",
    "Lumb A, Halliwell D, Sharma T: Application of CCME Water Quality Index to monitor water quality: a case study of the Mackenzie River Basin, Canada. Environ. Monit. Assess., 113(1–3), 411–429, 2006. doi:10.1007/s10661-005-9092-6",
    "Hurley T, Sadiq R, Mazumder A: Adaptation and evaluation of the Canadian Council of Ministers of the Environment Water Quality Index (CCME WQI) for use as an effective tool to characterize drinking source water quality. Water Res., 46(11), 3544–3552, 2012. doi:10.1016/j.watres.2012.03.061",
    "Gilliom RJ, Helsel DR: Estimation of distributional parameters for censored trace level water quality data: 1. Estimation techniques. Water Resour. Res., 22(2), 135–146, 1986. doi:10.1029/WR022i002p00135",
    "Helsel DR: More than obvious: better methods for interpreting nondetect data. Environ. Sci. Technol., 39(20), 419A–423A, 2005. doi:10.1021/es053368a",
    "Antweiler RC, Taylor HE: Evaluation of statistical treatments of left-censored environmental data using coincident uncensored data sets: I. Summary statistics. Environ. Sci. Technol., 42(10), 3732–3738, 2008. doi:10.1021/es071301c",
    "Smedley PL, Kinniburgh DG: A review of the source, behaviour and distribution of arsenic in natural waters. Appl. Geochem., 17(5), 517–568, 2002. doi:10.1016/S0883-2927(02)00018-5",
    "Bundschuh J, Litter MI, Parvez F, et al.: One century of arsenic exposure in Latin America: a review of history and occurrence from 14 countries. Sci. Total Environ., 429, 2–35, 2012. doi:10.1016/j.scitotenv.2011.06.024",
    "Litter MI, Ingallinella AM, Olmos V, et al.: Arsenic in Argentina: occurrence, human health, legislation and determination. Sci. Total Environ., 676, 756–766, 2019. doi:10.1016/j.scitotenv.2019.04.262",
    "Flexer V, Baspineiro CF, Galli CI: Lithium recovery from brines: a vital raw material for green energies with a potential environmental impact in its mining and processing. Sci. Total Environ., 639, 1188–1204, 2018. doi:10.1016/j.scitotenv.2018.05.223",
    "Ward MH, Jones RR, Brender JD, et al.: Drinking water nitrate and human health: an updated review. Int. J. Environ. Res. Public Health, 15(7), 1557, 2018. doi:10.3390/ijerph15071557",
    "Hem JD: Study and Interpretation of the Chemical Characteristics of Natural Water. 3rd ed., U.S. Geological Survey Water-Supply Paper 2254, Alexandria, USA, 1985. doi:10.3133/wsp2254",
    "Hayashi M: Temperature-electrical conductivity relation of water for environmental monitoring and geophysical data inversion. Environ. Monit. Assess., 96(1–3), 119–128, 2004. doi:10.1023/B:EMAS.0000031719.83065.68",
    "Walton NRG: Electrical conductivity and total dissolved solids—what is their precise relationship? Desalination, 72(3), 275–292, 1989. doi:10.1016/0011-9164(89)80012-8",
    "Fritz SJ: A survey of charge-balance errors on published analyses of potable ground and surface waters. Ground Water, 32(4), 539–546, 1994. doi:10.1111/j.1745-6584.1994.tb00888.x",
    "Wilson G, Aruliah DA, Brown CT, et al.: Best practices for scientific computing. PLoS Biol., 12(1), e1001745, 2014. doi:10.1371/journal.pbio.1001745",
    "Ziemann M, Eren Y, El-Osta A: Gene name errors are widespread in the scientific literature. Genome Biol., 17, 177, 2016. doi:10.1186/s13059-016-1044-7",
    "Sandve GK, Nekrutenko A, Taylor J, Hovig E: Ten simple rules for reproducible computational research. PLoS Comput. Biol., 9(10), e1003285, 2013. doi:10.1371/journal.pcbi.1003285",
    "Lamprecht A-L, Garcia L, Kuzak M, et al.: Towards FAIR principles for research software. Data Sci., 3(1), 37–59, 2020. doi:10.3233/DS-190026",
    "Parkhurst DL, Appelo CAJ: Description of Input and Examples for PHREEQC Version 3—A Computer Program for Speciation, Batch-Reaction, One-Dimensional Transport, and Inverse Geochemical Calculations. U.S. Geological Survey Techniques and Methods, Book 6, Chapter A43, Denver, USA, 2013. doi:10.3133/tm6A43",
    "Yang J, Liu H, Tang Z, Peeters L, Ye M: Visualization of aqueous geochemical data using Python and WQChartPy. Groundwater, 60(4), 555–564, 2022. doi:10.1111/gwat.13185",
  ],
};
